### PR TITLE
Follows

### PR DESCRIPTION
**Pull request by imperatrona**
add method for getting user follows and followers

### CODE REVIEW

**Comment by wade-liwei** [comment]
How do you get Authentication msg?
I try  username and cookie ,but failed.
Please share me an example.

**Comment by wade-liwei** [comment]
How do you get the request URL?

https://twitter.com/i/api/graphql/jwbfbSzn0FRL_AMZGsYDag/Followers

I tried the URL https://github.com/fa0311/TwitterInternalAPIDocument/blob/master/docs/markdown/GraphQL.md#followers but failed.

Do you have a document?
I want to get the other URL.

**Comment by imperatrona** [comment]
@wade-liwei It's probably failed caused of lack of param `variables` in your request. TwitterInternalAPIDocument is a great project but it doesn't have required variables.

Use Network tab in Developer Tools (Alt+Ctrl+I). Go to page that have required data, and then look for request that you need. In Payload tab you will find all data twitter required for this endpoint.

https://github.com/imperatrona/twitter-scraper/assets/37719998/b62e804b-4c1a-4bbe-97a1-0b25994393d3

**Comment by wade-liwei** [comment]
thank you make the video for me.

So can I use the post method like post twitter or retwitter by the browser Developer Tools?

**Comment by imperatrona** [comment]
@wade-liwei Yes you can create new methods by copying requests data from Developer Tools. If you implement new methods please maake pull request, i will be grateful!

ps. i just now added `CreateTweet`, `DeleteTweet`, `CreateRetweet` and `DeleteRetweet` methods wich works with previuosly implemented `UploadMedia`. also `CreateScheduledTweet`, `DeleteScheduledTweet` and `FetchScheduledTweets` is available

**Comment by wade-liwei** [comment]
Got it, thank you.

If I need to  implement new methods, I will do and make a pull request.

thanks for your project help me.

**Comment by wade-liwei** [comment]
Could you please help me to resolve my problem.

right now, I can get the user's followers with my backend service, then I need to bind the follower with the real twitter account in my app. 

I want to use twitter Oauth 2.0, but we just get the name field from Oauth 2.0.  I found out the API  https://api.twitter.com/2/users/me , but I am not sure how to use it after  login with twitter Oauth 2.0 on the app(https://dashboard-1-gray.vercel.app/login), and not sure can resolve my problem.

**Comment by imperatrona** [comment]
@wade-liwei with oauth2 you recieve authorization code wich you can use to create access token (Step 3 at this article - https://developer.x.com/en/docs/authentication/oauth-2-0/user-access-token)

and then you should make requests to api with access token in header `Authorization`

```golang
token := "auth_token"
req, err := http.NewRequest("GET", "https://api.twitter.com/2/users/me", nil)
req.Header.Set("Authorization", fmt.Sprintf("Bearer %s", token))

client := &http.Client{}
resp, err := client.Do(req)
```

i’m also recomend you to use user ids intead of usernames for binding users, since usernames changeble it can cause a lot of problems.

**Comment by wade-liwei** [comment]
1. Got it, thank you.

2. I will use use user ids instead of usernames for binding users.

3. https://api.twitter.com/2/users/me

     X API v2 
      free     25 requests / 24 hours PER USER.        0.0002/s
      basic   250 requests / 24 hours PER USER.      0.002/s
      pro    75 requests / 15 mins. PER USER.            0.08/s
 
 Do you have a good solution or a free solution without the rate limiter ?

**Comment by wade-liwei** [comment]
I want to try the twitter OAuth 1.0 .

**Comment by wade-liwei** [comment]
Hey @imperatrona 
I got the user ID "VXNlcjoxNTM1NjQyMTUyNTY2MjU5NzEy"  by twitter-scraper.

I got the user ID "1535642152566259712" by https://developer.x.com/en/docs/twitter-api/users/lookup/api-reference/get-users-me.

how to do compare?

**Comment by wade-liwei** [comment]
Hey bro @imperatrona

How to Rt , likes comments on the tweets?

**Comment by wade-liwei** [comment]
Hey @imperatrona 

Do you have a document about how to implement like(FavoriteTweet) interface?

**Comment by imperatrona** [comment]
@wade-liwei 

hi! sorry it’s not implemented yet. if you want you can implement this feature by yourself. you can do it by using Developer Tools - like/unlike tweet and copy the request data to new methods. please make a pull request if you implement this

**Comment by imperatrona** [comment]
hey @wade-liwei 
As I was implementing today new `GetSpace` method, i also added `LikeTweet` and `UnlikeTweet`, you can read more here - https://github.com/imperatrona/twitter-scraper?tab=readme-ov-file#like-tweet

**Comment by wade-liwei** [comment]
got it. thank you.

**Comment by wade-liwei** [comment]
Thank you so much.

Do you know there is a users list that have liked a Tweet and a users list that have Retweeted a Tweet?

**Pull request merged**
